version: '3.8'

services:
  # 資料庫服務
  db:
    image: mysql:latest
    container_name: order-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"

  # 快取服務
  cache:
    image: redis:latest
    container_name: order-redis
    ports:
      - "6379:6379"